### ISSUE TITLE
Vérification de l’insertion correcte de différentes balises Meta (Keywords, title, description) et open graph

### ISSUE THREAD

**Issue by Vince-CDA** [Vince-CDA/projetFilRouge#44]
- [x] Mettre en place des meta og (Open Graphe): pour être visible par les moteurs de recherches (facebook le fait, le gov aussi)
- [x] Vérification de l’insertion correcte de différentes balises Meta (Keywords, title,
- [x] description) et open graph
- [ ]
